require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FlowGrantsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # FlowGrant. As you add validations to FlowGrant, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FlowGrantsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all flow_grants as @flow_grants" do
      flow_grant = FlowGrant.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:flow_grants)).to eq([flow_grant])
    end
  end

  describe "GET #show" do
    it "assigns the requested flow_grant as @flow_grant" do
      flow_grant = FlowGrant.create! valid_attributes
      get :show, params: {id: flow_grant.to_param}, session: valid_session
      expect(assigns(:flow_grant)).to eq(flow_grant)
    end
  end

  describe "GET #new" do
    it "assigns a new flow_grant as @flow_grant" do
      get :new, params: {}, session: valid_session
      expect(assigns(:flow_grant)).to be_a_new(FlowGrant)
    end
  end

  describe "GET #edit" do
    it "assigns the requested flow_grant as @flow_grant" do
      flow_grant = FlowGrant.create! valid_attributes
      get :edit, params: {id: flow_grant.to_param}, session: valid_session
      expect(assigns(:flow_grant)).to eq(flow_grant)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new FlowGrant" do
        expect {
          post :create, params: {flow_grant: valid_attributes}, session: valid_session
        }.to change(FlowGrant, :count).by(1)
      end

      it "assigns a newly created flow_grant as @flow_grant" do
        post :create, params: {flow_grant: valid_attributes}, session: valid_session
        expect(assigns(:flow_grant)).to be_a(FlowGrant)
        expect(assigns(:flow_grant)).to be_persisted
      end

      it "redirects to the created flow_grant" do
        post :create, params: {flow_grant: valid_attributes}, session: valid_session
        expect(response).to redirect_to(FlowGrant.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved flow_grant as @flow_grant" do
        post :create, params: {flow_grant: invalid_attributes}, session: valid_session
        expect(assigns(:flow_grant)).to be_a_new(FlowGrant)
      end

      it "re-renders the 'new' template" do
        post :create, params: {flow_grant: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested flow_grant" do
        flow_grant = FlowGrant.create! valid_attributes
        put :update, params: {id: flow_grant.to_param, flow_grant: new_attributes}, session: valid_session
        flow_grant.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested flow_grant as @flow_grant" do
        flow_grant = FlowGrant.create! valid_attributes
        put :update, params: {id: flow_grant.to_param, flow_grant: valid_attributes}, session: valid_session
        expect(assigns(:flow_grant)).to eq(flow_grant)
      end

      it "redirects to the flow_grant" do
        flow_grant = FlowGrant.create! valid_attributes
        put :update, params: {id: flow_grant.to_param, flow_grant: valid_attributes}, session: valid_session
        expect(response).to redirect_to(flow_grant)
      end
    end

    context "with invalid params" do
      it "assigns the flow_grant as @flow_grant" do
        flow_grant = FlowGrant.create! valid_attributes
        put :update, params: {id: flow_grant.to_param, flow_grant: invalid_attributes}, session: valid_session
        expect(assigns(:flow_grant)).to eq(flow_grant)
      end

      it "re-renders the 'edit' template" do
        flow_grant = FlowGrant.create! valid_attributes
        put :update, params: {id: flow_grant.to_param, flow_grant: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested flow_grant" do
      flow_grant = FlowGrant.create! valid_attributes
      expect {
        delete :destroy, params: {id: flow_grant.to_param}, session: valid_session
      }.to change(FlowGrant, :count).by(-1)
    end

    it "redirects to the flow_grants list" do
      flow_grant = FlowGrant.create! valid_attributes
      delete :destroy, params: {id: flow_grant.to_param}, session: valid_session
      expect(response).to redirect_to(flow_grants_url)
    end
  end

end
